#!/bin/sh
chmod +x */All*
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

./makeMesh
runApplication decomposePar
runApplication mpirun -np 4 simpleFoam -parallel
runApplication reconstructPar

#------------------------------------------------------------------------------
